# Generated by Django 4.1.2 on 2022-10-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_description',
        ),
        migrations.AddField(
            model_name='product',
            name='anons_eng',
            field=models.CharField(default='Best choice', max_length=300, verbose_name='anons_eng'),
        ),
        migrations.AddField(
            model_name='product',
            name='anons_fi',
            field=models.CharField(default='Best choice', max_length=300, verbose_name='anons_fi'),
        ),
        migrations.AddField(
            model_name='product',
            name='guaranty',
            field=models.BooleanField(default='False', verbose_name='guaranty'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.CharField(default='', max_length=400, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.CharField(default='', max_length=400, verbose_name='image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.CharField(default='', max_length=400, verbose_name='image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description_eng',
            field=models.TextField(default='', verbose_name='Main_description_eng'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description_fi',
            field=models.TextField(default='', verbose_name='Main_description_fi'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_center',
            field=models.BooleanField(default='False', verbose_name='service_center'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=100, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='', max_length=100, verbose_name='weight'),
        ),
    ]
