# Generated by Django 4.1.2 on 2022-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_price_alter_product_anons_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=16, verbose_name='price'),
        ),
    ]
