# Generated by Django 4.1.2 on 2022-10-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_category_alter_product_guaranty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=16, verbose_name='category'),
        ),
    ]
