# Generated by Django 4.1.2 on 2022-10-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('computers', 'Computers'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=10, verbose_name='category'),
        ),
    ]
