# Generated by Django 4.1.2 on 2022-10-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.FileField(max_length=400, upload_to='', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.FileField(max_length=400, upload_to='', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.FileField(max_length=400, upload_to='', verbose_name='image3'),
        ),
    ]
