# Generated by Django 4.1.2 on 2022-10-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_id_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
