# Generated by Django 4.1.2 on 2022-11-03 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='anons_fi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_description_eng',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_description_fi',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_added'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_update'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description1',
            field=models.TextField(default='Best product', verbose_name='Main_description1'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description2',
            field=models.TextField(default='Best product', verbose_name='Main_description2'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description3',
            field=models.TextField(default='Best product', verbose_name='Main_description3'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description_name1',
            field=models.CharField(default='Best product', max_length=400, verbose_name='Main_description_name1'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description_name2',
            field=models.CharField(default='Best product', max_length=400, verbose_name='Main_description_name2'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_description_name3',
            field=models.CharField(default='Best product', max_length=400, verbose_name='Main_description_name3'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_feature1',
            field=models.CharField(default='Best product', max_length=200, verbose_name='main_feature1'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_feature2',
            field=models.CharField(default='Best product', max_length=200, verbose_name='main_feature2'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_feature3',
            field=models.CharField(default='Best product', max_length=200, verbose_name='main_feature3'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_include',
            field=models.CharField(default='Best product', max_length=300, verbose_name='package_include'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_with_package',
            field=models.CharField(default='Contact customer service', max_length=100, verbose_name='size_with_package'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description1',
            field=models.TextField(default='Best product', verbose_name='technical_description1'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description2',
            field=models.TextField(default='Best product', verbose_name='technical_description2'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description3',
            field=models.TextField(default='Best product', verbose_name='technical_description3'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description_name1',
            field=models.CharField(default='Best product', max_length=400, verbose_name='technical_description_name1'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description_name2',
            field=models.CharField(default='Best product', max_length=400, verbose_name='technical_description_name2'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description_name3',
            field=models.CharField(default='Best product', max_length=400, verbose_name='technical_description_name3'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_with_package',
            field=models.CharField(default='Contact customer service', max_length=100, verbose_name='weight_with_package'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=10, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guaranty',
            field=models.CharField(default='2 years', max_length=400, verbose_name='guaranty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_center',
            field=models.CharField(default='No', max_length=400, verbose_name='service_center'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='Best product', max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='Best product', max_length=100, verbose_name='weight'),
        ),
    ]
