# Generated by Django 4.1.2 on 2022-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_anons_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='guaranty',
            field=models.CharField(max_length=400, verbose_name='guaranty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description1',
            field=models.TextField(verbose_name='Main_description1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description2',
            field=models.TextField(verbose_name='Main_description2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description3',
            field=models.TextField(verbose_name='Main_description3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description_name1',
            field=models.CharField(max_length=400, verbose_name='Main_description_name1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description_name2',
            field=models.CharField(max_length=400, verbose_name='Main_description_name2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_description_name3',
            field=models.CharField(max_length=400, verbose_name='Main_description_name3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_feature1',
            field=models.CharField(max_length=200, verbose_name='main_feature1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_feature2',
            field=models.CharField(max_length=200, verbose_name='main_feature2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_feature3',
            field=models.CharField(max_length=200, verbose_name='main_feature3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_include',
            field=models.CharField(max_length=300, verbose_name='package_include'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_center',
            field=models.CharField(max_length=400, verbose_name='service_center'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_with_package',
            field=models.CharField(max_length=100, verbose_name='size_with_package'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description1',
            field=models.TextField(verbose_name='technical_description1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description2',
            field=models.TextField(verbose_name='technical_description2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description3',
            field=models.TextField(verbose_name='technical_description3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description_name1',
            field=models.CharField(max_length=400, verbose_name='technical_description_name1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description_name2',
            field=models.CharField(max_length=400, verbose_name='technical_description_name2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_description_name3',
            field=models.CharField(max_length=400, verbose_name='technical_description_name3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_with_package',
            field=models.CharField(max_length=100, verbose_name='weight_with_package'),
        ),
    ]
