# Generated by Django 4.1.2 on 2022-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_guaranty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Category id')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category name')),
                ('parent_category', models.CharField(choices=[('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=100, verbose_name='Parent category')),
            ],
        ),
    ]
