# Generated by Django 4.1.2 on 2022-11-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home'), ('Huawey Mobile', 'Huawey Mobile'), ('Peli lapparit', 'Peli lapparit'), ('Lena', 'Lena'), ('Ad', 'Ad'), ('Fufu', 'Fufu'), ('Fufu', 'Fufu'), ('Lala', 'Lala'), ('Mobile', 'Mobile'), ('Computers', 'Computers'), ('Laptops', 'Laptops'), ('TV/Audio', 'TV/Audio'), ('Home', 'Home'), ('Children', 'Children'), ('TEST', 'TEST')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.CharField(choices=[('no_parent', 'No_parent'), ('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=100, verbose_name='Parent category'),
        ),
    ]
