# Generated by Django 4.1.2 on 2022-11-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_category_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(choices=[('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home'), ('63518442', 'Huawey Mobile'), ('50568075', 'Peli lapparit'), ('35735457', 'Lena'), ('24940335', 'Ad'), ('26740598', 'Fufu'), ('21068026', 'Fufu'), ('80208590', 'Lala'), ('78561641', 'Mobile'), ('61508261', 'Computers'), ('46375989', 'Laptops'), ('99777023', 'TV/Audio'), ('89207485', 'Home'), ('45537497', 'Children'), ('75163756', 'TEST')], max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
    ]
