# Generated by Django 4.1.2 on 2022-11-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_productcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.CharField(choices=[('no_parent', 'No_parent'), ('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=100, verbose_name='parent category'),
        ),
    ]
