# Generated by Django 4.1.2 on 2022-11-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_productcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
    ]
