# Generated by Django 4.1.2 on 2022-11-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_productcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.CharField(blank=True, choices=[('no_parent', 'no_parent'), ('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home', 'Home')], max_length=100, null=True, verbose_name='Parent category'),
        ),
    ]
