# Generated by Django 4.1.2 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_productcategory_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.CharField(choices=[('main', 'Main'), ('mobile', 'Mobile'), ('computers', 'Computers'), ('laptops', 'Laptops'), ('tv/video', 'TV/Video'), ('audio', 'Audio'), ('home tech', 'Home tech'), ('children', 'Children')], max_length=100, verbose_name='Parent category'),
        ),
    ]
