# Generated by Django 4.1.2 on 2022-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_orders_items_total_orders_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='type_of_delivery',
            field=models.CharField(choices=[('post', 'Post'), ('matkahuolto', 'Matkahuolto'), ('DHL', 'DHL'), ('shop_pickup', 'Shop pickup')], default='post', max_length=100, verbose_name='Order payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pickup payment', 'Pickup payment')], default='unpaid', max_length=100, verbose_name='Order payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('shipped', 'Shipped'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('received', 'Received')], default='new', max_length=100, verbose_name='Order status'),
        ),
    ]
