# Generated by Django 4.1.2 on 2022-12-21 15:47
from django.db.models.signals import post_migrate
from django.db import migrations
from django.db import models

import json
from django.db.models.signals import post_migrate





def ready(self):
    post_migrate.connect(populate_database, sender=self)


def populate_database(apps, schema_editor):
    Category = apps.get_model('main', 'ProductCategory')
    db_alias = schema_editor.connection.alias

    with open('main_productcategory.json') as category_file:

        data = json.load(category_file)
        print(data)

    for i in range(0, len(data)):
        print(data[i]['category_id'])
        Category.objects.using(db_alias).bulk_create([

            Category(category_id=data[i]['category_id'], category_name=data[i]['category_name'],
                     parent_category=data[i]['parent_category'])
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_orders_type_of_delivery_alter_orders_payment_and_more'),
    ]

    operations = [migrations.RunPython(populate_database)
                 ]








